# Generated by Django 4.2.7 on 2023-11-10 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("press", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jouranlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("journalist_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("subscriber_count", models.IntegerField(default=0)),
                ("article_count", models.IntegerField(default=0)),
                ("cheer_count", models.IntegerField(default=0)),
                (
                    "press",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="press.press",
                        to_field="press_name",
                    ),
                ),
            ],
        ),
    ]
