# Generated by Django 4.2.7 on 2023-11-10 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("press", "0002_jouranlist"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Jouranlist",
            new_name="Journalist",
        ),
    ]
