# Generated by Django 4.2.7 on 2023-11-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("press", "0003_rename_jouranlist_journalist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalist",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
