# Generated by Django 4.2.7 on 2023-11-10 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("press", "0004_alter_journalist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="press",
            name="category",
            field=models.ForeignKey(
                db_column="category_name",
                on_delete=django.db.models.deletion.CASCADE,
                to="press.category",
                to_field="category_name",
            ),
        ),
    ]
