# Generated by Django 4.2.7 on 2023-11-12 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("press", "0008_section_journalistsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="age",
            name="journalist",
            field=models.ForeignKey(
                db_column="journalist_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="age",
                to="press.journalist",
                to_field="journalist_id",
            ),
        ),
        migrations.AlterField(
            model_name="gender",
            name="journalist",
            field=models.ForeignKey(
                db_column="journalist_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gender",
                to="press.journalist",
                to_field="journalist_id",
            ),
        ),
        migrations.AlterField(
            model_name="journalist",
            name="press",
            field=models.ForeignKey(
                db_column="press_name",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journalist",
                to="press.press",
                to_field="press_name",
            ),
        ),
        migrations.AlterField(
            model_name="journalistsection",
            name="journalist",
            field=models.ForeignKey(
                db_column="journalist_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journalistsection",
                to="press.journalist",
                to_field="journalist_id",
            ),
        ),
        migrations.AlterField(
            model_name="journalistsection",
            name="section",
            field=models.ForeignKey(
                db_column="section_name",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journalistsection",
                to="press.section",
                to_field="section_name",
            ),
        ),
        migrations.AlterField(
            model_name="press",
            name="category",
            field=models.ForeignKey(
                db_column="category_name",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="press",
                to="press.category",
                to_field="category_name",
            ),
        ),
    ]
