name: CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'app/**'
      - '.github/workflows/main.yml'


permissions: write-all

env:
  IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/ci_test

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag ${{ env.IMAGE }}:latest \
            --file ./app/Dockerfile \
            "./app"
      - name: Push image
        run: |
          docker push ${{ env.IMAGE }}:latest

  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag ${{ env.IMAGE }}:latest \
            --file ./app/Dockerfile \
            "./app"
      - name: Run container
        run: |
          docker run \
            -itd \
            --name press_leaderboard \
            -p 8555:8000 \
            ${{ env.IMAGE }}:latest bash
      - name: Pytest
        run: docker exec press_leaderboard python -m pytest .
      - name: Flake8
        run: docker exec press_leaderboard python -m flake8 .
      - name: Black
        run: docker exec press_leaderboard python -m black . --check
      - name: isort
        run: docker exec press_leaderboard python -m isort . --check-only
